flowchart TD
Пошёл_дальше_и_погиб_в_схватке_с_тигром("Пошёл дальше и погиб в схватке с тигром")
Пошёл_дальше_и_погиб_в_схватке_с_тигром -- Конец игры --> Конец_игры
Первое_утро_на_острове("Первое утро на острове")
Первое_утро_на_острове -- Пойти в джунгли, на поиски воды и пищи --> Найти_в_джунглях_красные_плоды
Первое_утро_на_острове -- Осмотреть корабль --> Осмотр_корабля
Первое_утро_на_острове -- Развести костёр (требуется трут и хворост) --> Развёл_костёр
Попытка_осмотреться("Попытка осмотреться")
Попытка_осмотреться -- Ползти налево, к груде обломков --> Спасся_в_обломках
Попытка_осмотреться -- Ползти прямо, к джунглям --> Загрызли_дикие_звери
Попытка_осмотреться -- Так и ни на что и не решившись, снова потерять сознание от потери сил --> Смыло_штормом_в_океан
Осмотрелся_и_собрал_плоды("Осмотрелся и собрал плоды")
Осмотрелся_и_собрал_плоды -- Пойти дальше --> Пошёл_дальше_и_погиб_в_схватке_с_тигром
Осмотрелся_и_собрал_плоды -- Вернуться к берегу --> Вернулся_обратно_и_осмотрел_корабль
Попытка_открыть_глаза("Попытка открыть глаза")
Попытка_открыть_глаза -- Сквозь пелену в глазах попытаться осмотреться --> Попытка_осмотреться
Смыло_штормом_в_океан("Смыло штормом в океан")
Смыло_штормом_в_океан -- Конец игры --> Конец_игры
Найти_в_джунглях_красные_плоды("Найти в джунглях красные плоды")
Найти_в_джунглях_красные_плоды -- Карабкаться и сорвать плоды --> Осмотрелся_и_собрал_плоды
Найти_в_джунглях_красные_плоды -- Трясти дерево --> Получил_по_голове_красным_плодом
Найти_в_джунглях_красные_плоды -- Пойти дальше --> ПУСТО
Вернулся_обратно_и_осмотрел_корабль("Вернулся обратно и осмотрел корабль")
Вернулся_обратно_и_осмотрел_корабль -- Спокойной ночи! --> Второе_утро_на_острове
Конец_игры("Конец игры")
Загрызли_дикие_звери("Загрызли дикие звери")
Загрызли_дикие_звери -- Конец игры --> Конец_игры
Спасся_в_обломках("Спасся в обломках")
Спасся_в_обломках -- Лечь спать --> Первое_утро_на_острове
Начало("Начало")
Начало -- Собрав остатки сил с трудом открыть глаза и приподнять голову чтобы немного осмотреться... --> Попытка_открыть_глаза
Получил_по_голове_красным_плодом("Получил по голове красным плодом")
Получил_по_голове_красным_плодом -- Быть расплющенным красным плодом --> Конец_игры