flowchart TD
konets_igry("konets igry")
osmotrelsa_i_sorval_plody("osmotrelsa i sorval plody")
osmotrelsa_i_sorval_plody -- Пойти дальше --> poshel_dalshe_i_pogib_v_shvatke_s_tigrom
osmotrelsa_i_sorval_plody -- Вернуться к берегу --> vernulsya_obratno_i_osmotrel_korabl
osmotr_korablya("osmotr korablya")
osmotr_korablya -- Вернуться на берег --> pervoe_utro_na_ostrove
smilo_shtormom_v_okean("smilo shtormom v okean")
smilo_shtormom_v_okean -- Конец игры --> konets_igry
popitka_osmotretsa("popitka osmotretsa")
popitka_osmotretsa -- Ползти налево, к груде обломков --> spassya_v_oblomkah
popitka_osmotretsa -- Ползти прямо, к джунглям --> zagrizly_dikie_zveri
popitka_osmotretsa -- Так и ни на что и не решившись, снова потерять сознание от потери сил --> smilo_shtormom_v_okean
pervoe_utro_na_ostrove("pervoe utro na ostrove")
pervoe_utro_na_ostrove -- Пойти в джунгли, на поиски воды и пищи --> naiti_v_junglyah_krasnie_plody
pervoe_utro_na_ostrove -- Осмотреть корабль --> osmotr_korablya
pervoe_utro_na_ostrove -- Развести костёр (требуется трут и хворост) --> razvel_koster
poshel_dalshe_i_pogib_v_shvatke_s_tigrom("poshel dalshe i pogib v shvatke s tigrom")
poshel_dalshe_i_pogib_v_shvatke_s_tigrom -- Конец игры --> konets_igry
poshel_dalshe_i_bil_zadavlen_palmoy("poshel dalshe i bil zadavlen palmoy")
poshel_dalshe_i_bil_zadavlen_palmoy -- Конец игры --> konets_igry
spassya_v_oblomkah("spassya v oblomkah")
spassya_v_oblomkah -- Лечь спать --> pervoe_utro_na_ostrove
poluchil_po_golove_krasnim_plodom("poluchil po golove krasnim plodom")
poluchil_po_golove_krasnim_plodom -- Быть расплющенным красным плодом --> konets_igry
otpravilsa_v_more_i_pogib_ot_akuli("otpravilsa v more i pogib ot akuli")
otpravilsa_v_more_i_pogib_ot_akuli -- Конец игры --> konets_igry
vtoroe_utro_na_ostrove("vtoroe utro na ostrove")
vtoroe_utro_na_ostrove -- Отправиться в джунгли --> otpravilsa_v_jungli_i_nashel_kokosy_i_rodnik
vtoroe_utro_na_ostrove -- Отправиться в море на поиски трюма --> otpravilsa_v_more_i_pogib_ot_akuli
vernulsya_obratno_i_osmotrel_korabl("vernulsya obratno i osmotrel korabl")
vernulsya_obratno_i_osmotrel_korabl -- Спокойной ночи! --> vtoroe_utro_na_ostrove
otpravilsa_v_jungli_i_nashel_kokosy_i_rodnik("otpravilsa v jungli i nashel kokosy i rodnik")
otpravilsa_v_jungli_i_nashel_kokosy_i_rodnik -- Бить по кокосу камнем --> vskril_kokos_i_nashel_kokosovuyu_vodu
otpravilsa_v_jungli_i_nashel_kokosy_i_rodnik -- Сбросить кокос с возвышенности --> sbrosil_kokos_i_razbilsa
sbrosil_kokos_i_razbilsa("sbrosil kokos i razbilsa")
zagrizly_dikie_zveri("zagrizly dikie zveri")
zagrizly_dikie_zveri -- Конец игры --> konets_igry
nachalo("nachalo")
nachalo -- Собрав остатки сил с трудом открыть глаза и приподнять голову чтобы немного осмотреться... --> popitka_otkryt_glaza
popitka_otkryt_glaza("popitka otkryt glaza")
popitka_otkryt_glaza -- Сквозь пелену в глазах попытаться осмотреться --> popitka_osmotretsa
naiti_v_junglyah_krasnie_plody("naiti v junglyah krasnie plody")
naiti_v_junglyah_krasnie_plody -- Карабкаться и сорвать плоды --> osmotrelsa_i_sorval_plody
naiti_v_junglyah_krasnie_plody -- Трясти дерево --> poluchil_po_golove_krasnim_plodom
naiti_v_junglyah_krasnie_plody -- Пойти дальше --> poshel_dalshe_i_bil_zadavlen_palmoy